# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

- task: NuGetToolInstaller@1
  inputs:
    versionSpec: '5.2.0'

- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: 'SampleDatabaseProject.sln'
    feedsToUse: 'select'

- task: VSBuild@1
  inputs:
    solution: 'SampleDatabaseProject.sln'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'SampleDatabaseConsole\\bin\\Release\\'
    ArtifactName: 'SampleDatabaseConsole'
    publishLocation: 'Container'
